services:
  postgres:
    image: postgres:17
    container_name: orders-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: audit-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  orders-service:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    container_name: orders-service
    command: pnpm start:debug orders
    environment:
      SERVICE_NAME: orders-service
      ORDERS_PORT: ${ORDERS_PORT}
      AUDIT_TCP_HOST: audit-service
      AUDIT_TCP_PORT: ${AUDIT_TCP_PORT}
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
  audit-service:
    build:
      context: .
      dockerfile: ./apps/audit/Dockerfile
      target: development
    container_name: audit-service
    command: pnpm start:debug audit
    environment:
      SERVICE_NAME: audit-service
      AUDIT_PORT: ${AUDIT_PORT}
      AUDIT_TCP_PORT: ${AUDIT_TCP_PORT}
    ports:
      - '3001:3001'
      - '4000:4000'
      - '9230:9229'
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
  mongodb_data:
